# Generated by Django 5.1.6 on 2025-02-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
    ]
